sudo: false
language: julia
julia:
 - 0.7
 - 1.0
 - nightly
before_install:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
addons:
  apt:
    packages:
      - hdf5-tools
script:
 - julia --check-bounds=yes -e 'versioninfo(); using Pkg; Pkg.clone(pwd()); Pkg.build("GaussianMixtures"); Pkg.test("GaussianMixtures", coverage=true)'
